project:
  type: website
  render: 
    - index.qmd

website:
  title: "mJ peerR vol.4"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://github.com/mokztk/mJ_Rpeer_2025Mar
        text: View Codes
        icon: github

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

